version: 2
project_name: changes
env:
  - CGO_ENABLED=0

before:
  hooks:
    - go run ./cmd/changes generate --check

builds:
  - id: changes
    main: ./cmd/changes
    binary: changes
    flags: [-trimpath]
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos: [darwin, linux]
    goarch: [amd64, arm64]
archives:
  - id: changes
    ids: [changes]
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - src: completions/*
        dst: completions
      - src: schema/*.cue
        dst: schema
      - src: schema/*.json
        dst: schema

checksum:
  name_template: checksums.txt

changelog:
  use: github-native
